parameters:
#    api.example.class: Ufuturelabs\Ufuturedesk\ApiBundle\Example

services:
#    api.example:
#        class: %api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
