oauth:
    resource: "@OAuthBundle/Resources/config/routing.yml"
    prefix:   /oauth

api:
    resource: "@SyncBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /sync/doc

teacher:
    resource: "@TeacherBundle/Resources/config/routing.yml"
    prefix:   /teacher

student:
    resource: "@StudentBundle/Resources/config/routing.yml"
    prefix:   /student

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
