teacher:
    resource: "@TeacherBundle/Resources/config/routing.yml"
    prefix:   /teacher

student:
    resource: "@StudentBundle/Resources/config/routing.yml"
    prefix:   /student

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
