security:
    encoders:
        Ufuturelabs\Ufuturedesk\MainBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_TEACHER: ROLE_STUDENT
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER]

    providers:
        users:
            entity:
                class: Ufuturelabs\Ufuturedesk\MainBundle\Entity\User
                property: userName

    firewalls:
        oauth_authorize:
            pattern: ^/oauth/v2/auth
            anonymous: true
            form_login:
                login_path: oauth_login
                check_path: oauth_login_check

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false

        user:
            pattern:  ^/*
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                success_handler: login_listener
            logout:
                path: user_logout
                target: user_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/teacher, roles: ROLE_TEACHER }
        - { path: ^/student, roles: ROLE_STUDENT }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
