parameters:
#    main.example.class: Ufuturelabs\Ufuturedesk\MainBundle\Example

services:
    login_listener:
        class: Ufuturelabs\Ufuturedesk\MainBundle\Listener\LoginListener
        arguments: [@router, @security.context]
        tags:
           - { name: 'monolog.logger', channel: 'security' }
