parameters:
#    main.example.class: Ufuturelabs\Ufuturedesk\MainBundle\Example

services:
    login_listener:
        class: Ufuturelabs\Ufuturedesk\MainBundle\Listener\LoginListener
        tags:
           - { name: kernel.event_listener, event: security.interactive_login }
           - { name: kernel.event_listener, event: kernel.response }

        arguments: [@logger, @router]
