parameters:
#    main.example.class: Ufuturelabs\Ufuturedesk\MainBundle\Example

services:
#    main.example:
#        class: %main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
