parameters:
#    sync.example.class: Ufuturelabs\Ufuturedesk\SyncBundle\Example

services:
#    sync.example:
#        class: %sync.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
