admin_admin_index:
    pattern: /
    defaults: { _controller: AdminBundle:Admin:index }

admin_admin_view:
    pattern: /view/{id}
    defaults: { _controller: AdminBundle:Admin:view }

admin_admin_create:
    pattern: /create
    defaults: { _controller: AdminBundle:Admin:create }

admin_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller: AdminBundle:Admin:view }

admin_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller: AdminBundle:Admin:view }

admin_school_edit:
    pattern: /edit/{id}
    defaults: { _controller: AdminBundle:Admin:edit }

admin_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller: AdminBundle:Admin:delete }
