admin_exam_index:
    path:     /
    defaults: { _controller: AdminBundle:Exam:index }

admin_exam_view:
    path:     /view/{id}
    defaults: { _controller: AdminBundle:Exam:view }

admin_exam_create:
    path:     /create
    defaults: { _controller: AdminBundle:Exam:create }

admin_exam_edit:
    path:     /edit/{id}
    defaults: { _controller: AdminBundle:Exam:edit }

admin_exam_delete:
    path:     /delete/{id}
    defaults: { _controller: AdminBundle:Exam:delete }