admin_index:
    pattern:  /
    defaults: { _controller: AdminBundle:Default:index }

admin_school:
    prefix: /school
    resource: "@AdminBundle/Resources/config/routing/school.yml"

admin_admin:
    prefix: /admin
    resource: "@AdminBundle/Resources/config/routing/admin.yml"
