admin_index:
    pattern:  /
    defaults: { _controller: AdminBundle:Default:index }

admin_school:
    prefix: /school
    resource: "@AdminBundle/Resources/config/routing/school.yml"

admin_admin:
    prefix: /admin
    resource: "@AdminBundle/Resources/config/routing/admin.yml"

admin_teacher:
    prefix: /teacher
    resource: "@AdminBundle/Resources/config/routing/teacher.yml"

admin_user_disable:
    path: /user/disable/{id}
    defaults: { _controller: "AdminBundle:Default:disableUser" }

admin_user_recovery_password:
    path: /user/recoverypassword/{id}
    defaults: { _controller: "AdminBundle:Default:recoveryPassword" }

admin_course:
    prefix: /course
    resource: "@AdminBundle/Resources/config/routing/course.yml"
